name: Setup node, pnpm and install
description: Github composite action to checkout, install node & pnpm (with cache) then run install (with frozen lockfile)
inputs:
  node-version:
    description: Node version
    required: false
    default: 22
  pnpm-version:
    description: Pnpm version
    required: false
    default: 9
  deno-enabled:
    description: Deno enabled, set env.DENO_DIR to deno_cache
    required: false
    default: false
  deno-version:
    description: Deno version
    required: false
    default: 2
runs:
  using: composite
  steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Cache Deno dependencies
      if: ${{ inputs.deno-enabled }}
      uses: actions/cache@v4
      with:
        path: deno_cache
        key: ${{ inputs.deno-enabled && hashFiles('deno.lock') || "no-deno" }}
    - name: Install deno
      if: ${{ inputs.deno-enabled }}
      uses: denoland/setup-deno@v2
      with:
        deno-version: v${{ inputs.deno-version }}.x
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}
    - name: Setup node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
    - name: Install
      run: pnpm install --frozen-lockfile
      shell: bash
